### ISSUE TITLE
Quickly press enter key output html code

### ISSUE THREAD

**Issue by Nauxscript** [Dashibase/lotion#6] opened 2022-07-29 09:30 UTC
![iShot_2022-07-29_17 24 24](https://user-images.githubusercontent.com/13010589/181729365-88572ed1-2e17-4e67-8b5a-6761f11d838f.gif)

**Comment by greentfrapp** [comment] 2022-08-01 11:43
Hi there! Can I check if this is still an issue for you in the [latest version](https://lotion.dashibase.com)?

**Comment by vvidday** [comment] 2022-08-01 16:14
hi @greentfrapp, the bug can still be reproduced by positioning cursor at the end of any line, pressing 'enter', then 'delete' and 'enter' twice more. seems to be an [intentional hack by prosemirror](https://discuss.prosemirror.net/t/parser-adds-br-tag-to-every-paragraph/1539) that is only getting triggered in the `merge` and  `split` functions and not getting picked up by the regex check `emit('update:modelValue', editor.value?.getHTML().replaceAll(/\<br.*?\>/g, ''))` in the editor for some reason.

Adding the same regex check to `merge` seems to fix the issue

**Comment by greentfrapp** [comment] 2022-08-01 17:32
Fixed with #26. Thanks @Nauxscript for reporting this and @vvidday for the fix! 🧴

**Closed by greentfrapp** 2022-08-01 17:32 UTC
